### ISSUE TITLE
Service level watchdog code

### ISSUE THREAD

**Issue by zhanif3** [HolmesProcessing/Holmes-Totem#1]
_From @webstergd on November 5, 2015 11:4_

Currently the system provides a generic watchdog based mostly on http response codes. This is great but not enough for many Services. For example, VT and Cuckoo.

We need the ability to add more fine-grained monitoring that is Service specific. 

_Copied from original issue: HolmesProcessing/Holmes-Totem-old#1_

**Comment by webstergd** [comment]
We need to standardize some of the error output codes. We currently deal with 404 and 500. Should we extent to support 400 

400 Bad Request input is invalid:
Used for when the input would provide false or misleading results. For example, a private IP address.

**Comment by zhanif3** [comment]
That's a good question. Do we want to validate user's input for them at a service or gateway level? Personally, I think the Gateway is preferable.

I do not think 400 is the code we want (the request itself is valid, after all, it's just business logic that's being violated). 

Come to think of it, I'd actually prefer to have validation happen at the service driver level, before we transmit to the Service itself. We could implement it as a part of the TaskedWork trait (https://github.com/HolmesProcessing/Holmes-Totem/blob/master/src/main/scala/org/novetta/zoo/types/WorkTypes.scala#L48), allowing users to select if they even want to call it, but giving them a clear manner and location in which to do so. This way, we never make the (even local) network call, and save a bit of processing time, and can immediately return a failure to the WorkActor's aggregating Future object.

**Comment by webstergd** [comment]
I worry about playing around with TaskedWork. If we start to validate ips, domains, samples, etc, I think it can quickly become overly complicated and difficult to handle new types that services can process. For example, If right now if I wanted a service that handled a memory dump, I can just write the service and don't really need to change much in core. If we perform validation in TaskedWork, then the pipe is no longer generic. 

Personally, I think we need 2 levels of validation
1) A gateway that validates tasking before it hits the Transport layer.
2) Each Service should then also validate tasking. Failed work should then be sent to the failed queue

I say this because we don't really want tasking to enter the transport layer if it cannot be handled. It would just clutter the queue. Additionally, we do want the complete system to validate that a user is able to submit tasking in the first place which will require a Gateway of some sort. Second, validating at a service level is pretty easy and if invalid tasking does bypass the gateway and hit a Service, it probably needs human intervention. 

As for HTTP codes: 
Invalid type like an IP address of 8.8.8.8.8 or a file that isn't available in the system, already returns a 404. This makes sense. 

Now for an unsupported query; such as a private ip address. I think we could use.
400 Bad Request
"The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing)."[36]
--or --
501 Not Implemented
The server either does not recognize the request method, or it lacks the ability to fulfill the request. Usually this implies future availability (e.g., a new feature of a web-service API).[78]

Thoughts?

**Comment by zhanif3** [comment]
Well, TaskedWork is just an interface, so we stub out a function, and let the user implement (or not, as needed). Something like def validate(thing: Any) is about as generic as it gets. If we validate at the Scala REST layer, however (via tasked work), we never need to stress the hosted Service. No logic is implemented in TaskedWork, it just gets implemented in the extending class, and we can use the existant service failure types to represent.

**Comment by webstergd** [comment]
Those are solid points and wont be difficult. I looked at some of the default libraries in Scala and it should also be pretty easy to implement some validation. 

What about providing validation at all three levels? 1) gateway, 2) planner, and 3) worker.

**Comment by zhanif3** [comment]
So, I rather expect that the Gateway and Planner will be heavily customized by users based on the data they are putting through, and their own needs. This fits the philosophy of letting users modify the services easily, and modify the data ingest easily. 

I think that, if anything, we should enforce things at the level of the planner, where ever possible, instead of enforcing at the other levels. This is mostly due to the fact that if we're publishing services, we want the implementation to conform as closely as possible to some kind of best practices. I think that we can call pruning data before the point of lowest bandwidth to be that.

**Comment by webstergd** [comment]
I am going to close this issue and create a development efforts in this direction. I will open new issues for each effort
