### ISSUE TITLE
Hardcoded /tmp in Services

### ISSUE THREAD

**Issue by ms-xy** [HolmesProcessing/Holmes-Totem#80]
Issue to document our discussion.

Right now, all services have a hard-coded /tmp for accessing files and they expect to only receive the SHA256 and then search at /tmp/hash for the file.

However, we could have services that consume so much system resources that we would opt to have them run on their own box instead of the Totem box.
As such they wouldn't be able to access /tmp.

One possible solution is to pass the Holmes-Storage URL to the service directly.
Another would be to supply them with an URL for a file server (like Tornado) that distributes the file from /tmp on the Totem box.

**Comment by webstergd** [comment]
The Planner is providing a RAM drive for performance reasons. Right now this is hard coded to /tmp. I could be convinced to adjust the location. However, my fear is that it would create additional work to maintain as all local services would also have to be in sync. This would be hard to automate because Docker currently had difficulty pulling files outside the their folder. 

That said, Zach pull request #96 does provide a flag for download. This removes the download requirement for remote services.
